export {
  applySelectionTarget,
  EMPTY_SELECTION_TARGET,
  isSelectionTargetEqual,
  normalizeSelectionTarget,
  deriveSelectionAffordance,
  deriveSelectionSummary,
  getTargetBounds,
  isSelectionAffordanceEqual,
  isSelectionSummaryEqual,
  resolveSelectionBoxTarget,
  resolveSelectionTransformBox,
  type SelectionInput,
  type BoundsTarget,
  type SelectionAffordance,
  type SelectionAffordanceMoveHit,
  type SelectionAffordanceOwner,
  type SelectionSummary,
  type SelectionTarget,
  type SelectionTransform,
  type SelectionTransformBox,
} from '#whiteboard-core/selection/model'
