export type ToolbarItemKey =
  | 'scope'
  | 'align'
  | 'group'
  | 'shape-kind'
  | 'font-size'
  | 'bold'
  | 'italic'
  | 'text-align'
  | 'text-color'
  | 'stroke'
  | 'fill'
  | 'edge-stroke'
  | 'edge-geometry'
  | 'edge-marker-start'
  | 'edge-marker-swap'
  | 'edge-marker-end'
  | 'edge-add-label'
  | 'edge-text-mode'
  | 'lock'
  | 'more'

export type ToolbarRecipeItem =
  | { kind: 'item'; key: ToolbarItemKey }
  | { kind: 'divider' }

export type ToolbarPanelKey =
  | 'scope'
  | 'align'
  | 'shape-kind'
  | 'font-size'
  | 'text-align'
  | 'text-color'
  | 'stroke'
  | 'fill'
  | 'edge-stroke'
  | 'edge-geometry'
  | 'edge-marker-start'
  | 'edge-marker-end'
  | 'more'
