export { Page } from '#react/page/Page.tsx'
export type { PageProps } from '#react/page/Page.tsx'
export { PageHeader } from '#react/page/Header.tsx'
export type { PageHeaderProps } from '#react/page/Header.tsx'
export { PageToolbar } from '#react/page/Toolbar.tsx'
export type { PageToolbarProps } from '#react/page/Toolbar.tsx'
export { PageBody } from '#react/page/Body.tsx'
export type { PageBodyProps } from '#react/page/Body.tsx'
